# Config file for automatic testing at travis-ci.org

language: python
python:
  - "3.6"
  - "3.7"

install:
  - wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-linux-64.exe -O conda.exe
  - chmod +x conda.exe
  - export CONDA_ALWAYS_YES=1
  # This is where you put any extra dependencies you may have.
  - ./conda.exe create -p $HOME/miniconda python=$TRAVIS_PYTHON_VERSION conda conda-build pytest six pytest-cov pytest-mock
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r 